### ISSUE TITLE
ErrorException  : mb_strpos() expects parameter 1 to be string, object given after running `php artisan postman:export`

### ISSUE THREAD

**Issue by sayasuhendra** [phpsa/laravel-postman#6]
after running

``
php artisan postman:export
``

i got

``
ErrorException  : mb_strpos() expects parameter 1 to be string, object given
``

![image](https://user-images.githubusercontent.com/4870292/103209931-d5dca180-4936-11eb-8118-384f88a287fa.png)

**Comment by phpsa** [comment]
Fixed in release 2.2.1
Thank you
